Repository canonical/github-runner-manager, pull requests merged in 2024-09, with the labels that each got.

#5 Issue reconciliation metric on error
  .github/workflows/test.yaml
  pyproject.toml
  src-docs/manager.runner_scaler.md
  src/github_runner_manager/manager/runner_scaler.py
  tests/unit/test_runner_scaler.py
Labels: bug, trivial

#7 fix: health check catch SSH Error
  pyproject.toml
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
Labels: bug

#10 feat: health check
  pyproject.toml
  src-docs/manager.cloud_runner_manager.md
  src-docs/openstack_cloud.openstack_cloud.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src/github_runner_manager/manager/cloud_runner_manager.py
  src/github_runner_manager/openstack_cloud/openstack_cloud.py
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  tests/unit/factories/openstack_factory.py
  tests/unit/requirements.txt
  tests/unit/test_openstack_runner_manager.py
  tox.ini
Labels: enhancement, complex

#11 fix: instance initialization cloud-init status check
  pyproject.toml
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
Labels: bug, urgent

#13 chore: verbose logging and timeout for ssh commands
  pyproject.toml
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
Labels: enhancement, trivial

#8 Spawn reactive runner
  pyproject.toml
  requirements.txt
  src-docs/github_client.md
  src-docs/manager.runner_manager.md
  src-docs/manager.runner_scaler.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src-docs/reactive.consumer.md
  src-docs/reactive.runner.md
  src-docs/reactive.runner_manager.md
  src-docs/reactive.types_.md
  src-docs/types_.general.md
  src-docs/types_.github.md
  src-docs/types_.md
  src/github_runner_manager/github_client.py
  src/github_runner_manager/manager/runner_manager.py
  src/github_runner_manager/manager/runner_scaler.py
  src/github_runner_manager/metrics/github.py
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  src/github_runner_manager/reactive/consumer.py
  src/github_runner_manager/reactive/runner.py
  src/github_runner_manager/reactive/runner_manager.py
  src/github_runner_manager/reactive/types_.py
  src/github_runner_manager/types_/__init__.py
  src/github_runner_manager/types_/github.py
  tests/unit/metrics/test_github.py
  tests/unit/reactive/test_consumer.py
  tests/unit/reactive/test_runner_manager.py
  tests/unit/test_github_client.py
  tests/unit/test_openstack_runner_manager.py
  tests/unit/test_runner_scaler.py
Labels: complex

#16 use url instead of job_url in JobDetails
  pyproject.toml
  src-docs/reactive.consumer.md
  src/github_runner_manager/openstack_cloud/openstack_cloud.py
  src/github_runner_manager/reactive/consumer.py
  src/github_runner_manager/utilities.py
  tests/unit/reactive/test_consumer.py
Labels: bug, trivial

#18 fix: revert kill commands to original
  pyproject.toml
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
Labels: bug, trivial, urgent

#17 feat: Job label validation
  pyproject.toml
  src-docs/openstack_cloud.openstack_runner_manager.md
  src-docs/reactive.consumer.md
  src-docs/reactive.types_.md
  src/github_runner_manager/github_client.py
  src/github_runner_manager/reactive/consumer.py
  src/github_runner_manager/reactive/runner.py
  src/github_runner_manager/reactive/types_.py
  tests/unit/reactive/test_consumer.py
Labels: complex
