Repository canonical/github-runner-manager, pull requests merged in 2024-10, with the labels that each got.

#23 fix: add apt-update to userdata
  pyproject.toml
  src/github_runner_manager/templates/openstack-userdata.sh.j2
Labels: trivial

#19 feat: Reactive reconcile
  pyproject.toml
  src-docs/reactive.consumer.md
  src-docs/reactive.process_manager.md
  src-docs/reactive.runner_manager.md
  src/github_runner_manager/manager/runner_manager.py
  src/github_runner_manager/manager/runner_scaler.py
  src/github_runner_manager/reactive/consumer.py
  src/github_runner_manager/reactive/process_manager.py
  src/github_runner_manager/reactive/runner.py
  src/github_runner_manager/reactive/runner_manager.py
  tests/unit/reactive/test_consumer.py
  tests/unit/reactive/test_process_manager.py
  tests/unit/reactive/test_runner_manager.py
Labels: complex

#21 feat: Adjustments for COS integration for reactive mode
  pyproject.toml
  src-docs/manager.runner_manager.md
  src-docs/manager.runner_scaler.md
  src-docs/metrics.events.md
  src-docs/metrics.runner.md
  src-docs/metrics.storage.md
  src-docs/openstack_cloud.constants.md
  src-docs/openstack_cloud.health_checks.md
  src-docs/openstack_cloud.openstack_cloud.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src-docs/reactive.process_manager.md
  src-docs/reactive.runner_manager.md
  src-docs/reactive.types_.md
  src-docs/types_.md
  src/github_runner_manager/manager/runner_manager.py
  src/github_runner_manager/manager/runner_scaler.py
  src/github_runner_manager/metrics/events.py
  src/github_runner_manager/metrics/runner.py
  src/github_runner_manager/metrics/storage.py
  src/github_runner_manager/openstack_cloud/constants.py
  src/github_runner_manager/openstack_cloud/health_checks.py
  src/github_runner_manager/openstack_cloud/openstack_cloud.py
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  src/github_runner_manager/reactive/process_manager.py
  src/github_runner_manager/reactive/runner_manager.py
  src/github_runner_manager/reactive/types_.py
  src/github_runner_manager/templates/openstack-userdata.sh.j2
  src/github_runner_manager/types_/__init__.py
  tests/unit/metrics/test_runner.py
  tests/unit/metrics/test_storage.py
  tests/unit/openstack_cloud/__init__.py
  tests/unit/openstack_cloud/test_health_checks.py
  tests/unit/openstack_cloud/test_openstack_runner_manager.py
  tests/unit/reactive/test_process_manager.py
  tests/unit/reactive/test_runner_manager.py
  tests/unit/test_openstack_runner_manager.py
Labels: senior-review-required

#12 Remove usage of clouds.yaml file to openstack connection
  pyproject.toml
  src-docs/openstack_cloud.md
  src-docs/openstack_cloud.openstack_cloud.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src/github_runner_manager/openstack_cloud/__init__.py
  src/github_runner_manager/openstack_cloud/openstack_cloud.py
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  src/github_runner_manager/utilities.py
  tests/unit/openstack_cloud/test_openstack_runner_manager.py
  tests/unit/test_github_client.py
  tests/unit/test_openstack_cloud.py
Labels: trivial

#26 fix: chown of existing reactive runner log dir
  pyproject.toml
  src/github_runner_manager/reactive/process_manager.py
Labels: bug, trivial

#25 fix: shorten instance id
  src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
Labels: bug, trivial

#27 fix: Use datetime.fromisoformat in server uniqueness check
  pyproject.toml
  src/github_runner_manager/openstack_cloud/openstack_cloud.py
Labels: bug, trivial, urgent

#28 Include number of expected runners in reconciliation metric
  pyproject.toml
  src-docs/manager.runner_scaler.md
  src-docs/metrics.events.md
  src/github_runner_manager/manager/runner_scaler.py
  src/github_runner_manager/metrics/events.py
Labels: trivial
